name: Windows (x64)

on:
  push:
      branches: 
        - "*"
      tags:
        - "*"
    
  pull_request:
      branches: 
        - "*"

jobs:
  build:
    name: Build
    runs-on: windows-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install with VCPKG
        run: |
          vcpkg install libprojectm --overlay-ports="${{ github.workspace }}/port"